{% set name = "scikit-mobility" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3506a550a18ee9e555d7a41a4cb6b588e876932618cc10d1fa83c17c192f5948
  

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - folium
    - geojson
    - geopandas
    - matplotlib-base
    - numpy
    - pandas
    - powerlaw
    - python
    - requests
    - rtree
    - scikit-learn
    - scipy
    - shapely
    - statsmodels
    - tqdm
    - python-igraph
    - h3-py
    - pyproj
    - fiona
    - python >=3.6

test:
  imports:
    - skmob
    - skmob.core
    - skmob.io
    - skmob.measures
    - skmob.models
    - skmob.preprocessing
    - skmob.privacy
    - skmob.tessellation
    - skmob.utils

about:
  home: https://github.com/scikit-mobility/scikit-mobility

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A toolbox for analyzing and processing mobility data.
  description: |
    scikit-mobility is a library for human mobility analysis in Python. The library allows to: (i) represent trajectories and mobility flows with 
    proper data structures, TrajDataFrame and FlowDataFrame; (ii) manage and manipulate mobility data of various formats 
    (call detail records, GPS data, data from social media, survey data, etc.); (ii) extract mobility metrics and patterns from data, both at 
    individual and collective level (e.g., length of displacements, characteristic distance, origin-destination matrix, etc.); (iii) generate 
    synthetic individual trajectories using standard mathematical models (random walk models, exploration and preferential return model, etc.);
    (iv) generate synthetic mobility flows using standard migration models (gravity model, radiation model, etc.); (v) assess the privacy risk 
    associated with a mobility data set.
  doc_url: https://github.com/scikit-mobility/scikit-mobility

extra:
  recipe-maintainers:
    - gbarlacchi
    - jonpappalord
    - pellungrobe
    - FilippoSimini
